export type GameLogCategory =
  | 'system'
  | 'quest'
  | 'economy'
  | 'goal'
  | 'market'
  | 'breeding'
  | 'hanhai'
  | 'village'
  | 'processing'
  | 'social'
  | 'guild'
  | 'museum'

export type GameLogTag =
  | 'late_game_cycle'
  | 'theme_week_started'
  | 'weekly_goals_refreshed'
  | 'weekly_budget_activated'
  | 'weekly_budget_expired'
  | 'weekly_metric_snapshot_archived'
  | 'weekly_risk_report'
  | 'goal_completed'
  | 'goal_unlock_hint'
  | 'economy_sink_guidance'
  | 'breeding_completed'
  | 'breeding_discovery'
  | 'breeding_mutation'
  | 'hanhai_relic_exploration'
  | 'hanhai_relic_milestone'
  | 'hanhai_treasure_map'
  | 'hanhai_cycle_tick'
  | 'village_project_completed'
  | 'village_project_donation'
  | 'village_project_donation_milestone'
  | 'village_project_maintenance_cycle'
  | 'village_project_weekly_summary'
  | 'guild_season_tick'
  | 'museum_operational_tick'
  | 'processing_seed_bonus'

export type GameLogMeta = Record<string, string | number | boolean | null | undefined>
